- name: Deploy to OpenShift
  hosts: localhost
  connection: local
  tasks:
    - name: Set KUBECONFIG environment variable
      set_fact:
        KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"

    - name: Add stable chart repo
      kubernetes.core.helm_repository:
        name: categories-microservice
        repo_url: "http://146.235.233.225:8081/repository/helm-repo/"
    - name: Deploy latest version of Grafana chart inside monitoring namespace with values
      kubernetes.core.helm:
        name: test
        chart_ref: categories-microservice/categories-microservice
        chart_version: 1.0.1
        release_namespace: abdeslam2002-dev
        state: present
        force: true
