- name: Deploy to OpenShift
  hosts: localhost
  connection: local
  tasks:
    - name: Set KUBECONFIG environment variable
      set_fact:
        KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"

    - name: Add stable chart repo
      kubernetes.core.helm_repository:
        name: spring-microservice
        repo_url: "https://abdeslammoukhliss.github.io/helm-charts/charts"

    - name: Deploy with Helm
      community.kubernetes.helm:
        name: "category-service"
        chart_ref: "spring-microservice/spring-microservice"
        namespace: "abdomokh38-dev"
        kubeconfig: "{{ KUBECONFIG }}"
        state: present
